---
- hosts: "localhost"
  gather_facts: false
  connection: local
  tasks:
  - name: Install k8s ansible dependences
    pip:
       name:
          - openshift
          - pyyaml
          - kubernetes

  - name: Create namespace LAB01
    kubernetes.core.k8s:
       name: lab01
       api_version: v1
       kind: Namespace
       state: present
